### ISSUE TITLE
Block of Raw Ore do not require a tool to mine

### ISSUE THREAD

**Issue by Byzantine2** [AllTheMods/AllTheOres#28]
Blocks of raw ore added by ATO do not require a tool to mine, unlike their vanilla counterparts, or the blocks of the same metal.  They are also slow to mine as a result.

![2022-06-23_19 07 28](https://user-images.githubusercontent.com/106778016/175430154-d9ada0d3-0e76-4098-9752-bf70f9389f5d.png)

**Comment by thevortex** [comment]
ok noted, will take care of it :)

**Comment by thevortex** [comment]
1.9.9c of alltheores resolves this, added missing mineable by pickaxe tag
