### ISSUE TITLE
[Compatibility] REI Startup Crash

### ISSUE THREAD

**Issue by Ghastly13** [AllTheMods/AllTheOres#46]
Crash on startup when used with Roughly Enough Items
Log:
[latest.log](https://github.com/user-attachments/files/16399041/latest.log)

**Comment by jeremiahwinsley** [comment]
> [05:29:46] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: inventoryessentials

Doesn't seem to be related to ATO.
