### ISSUE TITLE
[Bug]: Brass block from AllTheOres not working on compacting drawers

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/AllTheOres#58]
### Possible Fixes

Yes

### Modpack Version

ATM10 - 0.30

### What happened?

The brass from alltheores only works in compacting drawers as ingots and nuggets. Blocks do not work like the other kind of ores.

**Comment by DaddyLongspoon** [comment]
duplicate of[ AllTheMods/AllTheOres#59](https://github.com/AllTheMods/AllTheOres/issues/59)
