### ISSUE TITLE
[Bug]: Eternal Ore Hammer broken

### ISSUE THREAD

**Issue by tjosias** [AllTheMods/AllTheOres#60]
### Possible Fixes

Yes

### Modpack Version

ATM10 - 1.5

### What happened?

Used an Eternal Stella on a Platinum Ore Hammer. It took away the items durability, so far so good.... but when you use it manually with an ore to turn it into dust, the hammer simply disappears. 

When trying to use an Eternal Platinum Ore Hammer with recipes inside of AE2, it will give the following message in the chat box: 

![Screenshot 2024-10-23 210706](https://github.com/user-attachments/assets/57d3a7dc-6ba4-4a43-90bc-d525c0cadbe0)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/AllTheOres/issues/55
