### ISSUE TITLE
[Bug]: block of raw platinum ore mining level 

### ISSUE THREAD

**Issue by ExiHum** [AllTheMods/AllTheOres#63]
### Possible Fixes

Yes

### Modpack Version

ATM10 - 1.20

### What happened?

I don't know if it's intended or not but the block of raw platinum ore has a iron mining level while the platinum ore has a diamond mining level.

**Comment by Dr69onS6mur6i** [comment]
I could be wrong, but that might be intended. Don't ALL ore blocks (blocks of raw ore) have that level of mining required?

**Comment by Satherov** [comment]
Fixed in #78
